name: 'Run all tests'

on:
  workflow_dispatch:

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Java version
        run: java --version
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Check Chrome version
        run: chrome --version
